name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch: # Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run tests
        run: "deno test"

      - name: Build step
        run: |
          deno compile --target x86_64-unknown-linux-gnu  --allow-read --allow-write --output tcx-ls-linux-x86_64       main.ts
          deno compile --target aarch64-unknown-linux-gnu --allow-read --allow-write --output tcx-ls-linux-arm64        main.ts
          deno compile --target aarch64-apple-darwin      --allow-read --allow-write --output tcx-ls-macos-arm64        main.ts
          deno compile --target x86_64-apple-darwin       --allow-read --allow-write --output tcx-ls-macos-x86_64       main.ts
          deno compile --target x86_64-pc-windows-msvc    --allow-read --allow-write --output tcx-ls-windows-x86_64.exe main.ts

      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tcx-ls-linux-x86_64
            tcx-ls-linux-arm64
            tcx-ls-macos-arm64
            tcx-ls-macos-x86_64
            tcx-ls-windows-x86_64.exe
