name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch: # Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run tests
        run: "deno test"

      - name: Build step
        run: |
          deno compile --target x86_64-unknown-linux-gnu  --allow-read --allow-write --output tcx-ls-linux-x86_64       main.ts
          deno compile --target aarch64-unknown-linux-gnu --allow-read --allow-write --output tcx-ls-linux-arm64        main.ts
          deno compile --target aarch64-apple-darwin      --allow-read --allow-write --output tcx-ls-macos-arm64        main.ts
          deno compile --target x86_64-apple-darwin       --allow-read --allow-write --output tcx-ls-macos-x86_64       main.ts
          deno compile --target x86_64-pc-windows-msvc    --allow-read --allow-write --output tcx-ls-windows-x86_64.exe main.ts

      - name: Upload Linux x86_64
        uses: actions/upload-artifact@v4
        with:
          name: tcx-ls-linux-x86_64
          path: ./tcx-ls-linux-x86_64

      - name: Upload Linux arm64
        uses: actions/upload-artifact@v4
        with:
          name: tcx-ls-linux-arm64
          path: ./tcx-ls-linux-arm64

      - name: Upload macOS arm64
        uses: actions/upload-artifact@v4
        with:
          name: tcx-ls-macos-arm64
          path: ./tcx-ls-macos-arm64

      - name: Upload macOS x86_64
        uses: actions/upload-artifact@v4
        with:
          name: tcx-ls-macos-x86_64
          path: ./tcx-ls-macos-x86_64

      - name: Upload Windows x86_64
        uses: actions/upload-artifact@v4
        with:
          name: tcx-ls-windows-x86_64.exe
          path: ./tcx-ls-windows-x86_64.exe

  macos-universal-test:
    name: Build macOS Universal
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build macOS arm64 + x86_64
        run: |
          start=$(date +%s)
          deno compile --target aarch64-apple-darwin --allow-read --allow-write --output tcx-ls-macos-arm64 main.ts
          deno compile --target x86_64-apple-darwin --allow-read --allow-write --output tcx-ls-macos-x86_64 main.ts
          lipo -create -output tcx-ls-macos-universal tcx-ls-macos-arm64 tcx-ls-macos-x86_64
          end=$(date +%s)
          echo "⏱ Total build + lipo time: $((end - start)) seconds"

      - name: Upload Universal Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tcx-ls-macos-universal
          path: ./tcx-ls-macos-universal
          compression-level: 0